<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250516130403 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE book_category (book_id UUID NOT NULL, category_id INT NOT NULL, PRIMARY KEY(book_id, category_id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_1FB30F9816A2B381 ON book_category (book_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_1FB30F9812469DE2 ON book_category (category_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_64C19C15E237E06 ON category (name)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE book_category ADD CONSTRAINT FK_1FB30F9816A2B381 FOREIGN KEY (book_id) REFERENCES book (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE book_category ADD CONSTRAINT FK_1FB30F9812469DE2 FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER INDEX uniq_book_slug RENAME TO UNIQ_CBE5A331989D9B62
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE book_category DROP CONSTRAINT FK_1FB30F9816A2B381
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE book_category DROP CONSTRAINT FK_1FB30F9812469DE2
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE book_category
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE category
        SQL);
        $this->addSql(<<<'SQL'
            ALTER INDEX uniq_cbe5a331989d9b62 RENAME TO uniq_book_slug
        SQL);
    }
}
